### ISSUE TITLE
where is "rotary_emb"?

### ISSUE THREAD

**Issue by ScottishFold007** [jzhang38/TinyLlama#19] opened 2023-09-13 03:29 UTC
in "fused_rotary_embedding.py", where is the "rotary_emb"?
![image](https://github.com/jzhang38/TinyLlama/assets/36957508/bbe9c361-6e20-467a-a5de-160be0a856f6)

**Comment by jzhang38** [comment] 2023-09-13 05:32
Duplicate of this [issue](https://github.com/jzhang38/TinyLlama/issues/5)

**Closed by jzhang38** 2023-09-13 05:32 UTC
